# Site settings
title: Cabanon des Cerises
email: cabanondescerises@gmail.com
facebook: CabanonDesCerises.MontVentoux
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.cabanondescerises.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - "*.json"
  - "Gemfile"

sass:
  style: compressed